SELECT 
	O.BUKRS AS [Company Code],
	CONVERT(BIGINT, D.MATNR) AS [Material No]
	,D.WERKS AS [Plant]
	,D.LGORT AS [Storage Location]
	,ZP.LGOBE AS [Storage Location Desc]
	,M.EAN11 AS [ISBN]
	,M.ZZLONGTEXT AS [Description]
	,M.ZZPUBLISHER1+M.ZZPUBLISHER2+M.ZZPUBLISHER3 AS [Publisher]
	,M.ZZCOPYRIGHT AS [Copyright]
	,M.ZEIVR AS [Edition]
	,ISNULL(T.LBTXT, '') AS [Discipline]
	,M.WRKST AS [Subject]
	,G1.BEZEI AS [Book Type]
	,G2.BEZEI AS [Print Type]
	,G3.BEZEI AS [Material Type]
	,[Inventory Type] = CASE WHEN CHARINDEX('-', G4.BEZEI) = 0 THEN RTRIM(LTRIM(G4.BEZEI)) 
		ELSE RTRIM(LTRIM(SUBSTRING(G4.BEZEI, 1, CHARINDEX('-', G4.BEZEI) - 1))) END,
	[Discount %] = CASE WHEN CHARINDEX('-', G4.BEZEI) = 0 THEN ''
		ELSE RTRIM(LTRIM(SUBSTRING(G4.BEZEI, CHARINDEX('-', G4.BEZEI) + 1, LEN(G4.BEZEI)))) END
	,ISNULL(G5.BEZEI, '') AS [Level/Semester]
	,CAST(D.LABST AS INT) AS Qty
	,ISNULL(matdel.KBETRCE, celog.KBETR)AS [Unit Cost]
 FROM prd.MARD as D
		INNER JOIN (
			SELECT DISTINCT 
				CASE 
					WHEN LEFT(WERKS,1) = 'P'  THEN '2000'
					WHEN LEFT(WERKS,1) = 'D'  THEN '3000'
					WHEN LEFT(WERKS,1) = 'C'  THEN '4000' 
					ELSE '1000'
					END AS VKORG,
				WERKS, 
				LGORT
			FROM prd.MARD
			WHERE MANDT = '888'
		) AS V
			ON D.WERKS = V.WERKS
			AND D.LGORT = V.LGORT 
		LEFT JOIN prd.MVKE AS E
			ON D.MANDT = E.MANDT
			AND D.MATNR = E.MATNR
			AND V.VKORG = E.VKORG
			AND E.VTWEG = '22'			 
		INNER JOIN prd.MARA  AS M
			ON D.MANDT=M.MANDT 
			AND D.MATNR=M.MATNR		
		LEFT JOIN prd.TVM1T AS G1
			ON E.MANDT = G1.MANDT
			AND E.MVGR1 = G1.MVGR1
			AND G1.SPRAS = 'E'
		LEFT JOIN prd.TVM2T AS G2
			ON E.MANDT = G2.MANDT
			AND E.MVGR2 = G2.MVGR2
			AND G2.SPRAS = 'E'
		LEFT JOIN prd.TVM3T AS G3
			ON E.MANDT = G3.MANDT
			AND E.MVGR3 = G3.MVGR3
			AND G3.SPRAS = 'E'
		LEFT JOIN prd.TVM4T AS G4
			ON E.MANDT = G4.MANDT
			AND E.MVGR4 = G4.MVGR4
			AND G4.SPRAS = 'E'
		LEFT JOIN prd.TVM5T AS G5
			ON E.MANDT = G5.MANDT
			AND E.MVGR5 = G5.MVGR5
			AND G5.SPRAS = 'E'
		LEFT JOIN prd.ZMM_PLNTSLOC AS ZP
			ON  D.MANDT=ZP.MANDT 
			AND D.WERKS=ZP.WERKS 
			AND D.LGORT=ZP.LGORT
		LEFT JOIN prd.T024X as T
			on M.MANDT = T.MANDT
			AND M.LABOR = T.LABOR
			AND T.SPRAS = 'E'
		LEFT JOIN prd.TVKO as O
		ON
			O.VKORG = E.VKORG
			AND O.MANDT = D.MANDT
		LEFT JOIN 
			prd.ZMM_MATDEL matdel
		ON
			matdel.MANDT = D.MANDT
			AND matdel.MATNR = D.MATNR
		LEFT JOIN 
			prd.ZMM_MATLOGIC celog
		ON
			celog.MANDT = D.MANDT
			AND celog.MATNR = D.MATNR
WHERE D.LABST<>'0.000'
	AND D.MANDT = '888'
	AND D.WERKS NOT IN ('DL00', 'PA00')
	AND D.WERKS NOT LIKE '7%'
	AND O.BUKRS IS NOT NULL
ORDER BY 
	D.MATNR
	,ZP.WERKS 
	,ZP.LGORT